djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),

# Логин.
    path('login/', views.LoginView.as_view(), name='login'),
    # Логаут.
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # Изменение пароля.
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # Сообщение об успешном изменении пароля.
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Восстановление пароля.
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # Сообщение об отправке ссылки для восстановления пароля.
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # Вход по ссылке для восстановления пароля.
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Сообщение об успешном восстановлении пароля.
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', include('projectForDBD.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectForDBD/urls.py
from django.urls import path

from . import views

app_name = 'projectForDBD'

urlpatterns = [
    path('', views.index, name='index'),

    path('products/', views.product_list, name='product_list'),
    path('categories/', views.category_list, name='category_list'),
    path('suppliers/', views.supplier_list, name='supplier_list'),

    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/<int:pk>/', views.remove_from_cart, name='delete_from_cart'),
    path('cart/', views.show_cart, name='cart'),

    path('category/create/', views.category_create, name='category_create'),
    path('category/edit/<int:pk>/', views.category_edit, name='category_edit'),
    path('category/delete/<int:pk>/', views.category_delete, name='category_delete'),
    path('supplier/create/', views.supplier_create, name='supplier_create'),
    path('supplier/edit/<int:pk>/', views.supplier_edit, name='supplier_edit'),
    path('supplier/delete/<int:pk>/', views.supplier_delete, name='supplier_delete'),
    path('product/create/', views.product_create, name='product_create'),
    path('product/edit/<int:pk>/', views.product_edit, name='product_edit'),
    path('product/delete/<int:pk>/', views.product_delete, name='product_delete'),
]

templates/includes/footer.html
{% if page_obj and own_url %}
    <nav>
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                {% if page_obj.previous_page_number != 1 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ own_url }}&page=1">Первая</a>
                    </li>
                {% endif %}
                {% if page_obj.previous_page_number != 1%}
                    <li class="page-item disabled">
                        <span class="page-link">
                        ...
                        </span>
                    </li>
                {% endif %}
   
                <li class="page-item">
                    <a class="page-link" href="{{ own_url }}&page={{ page_obj.previous_page_number }}"> {{ page_obj.previous_page_number }}</a>
                </li>
            {% endif %}
            <li class="page-item disabled">
                <span class="page-link">
                    {{ page_obj.number }}
                </span>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ own_url }}&page={{ page_obj.next_page_number }}"> {{ page_obj.next_page_number }}</a>
                </li>
                {% if page_obj.next_page_number !=  page_obj.paginator.num_pages %}
                    <li class="page-item disabled">
                        <span class="page-link">
                        ...
                        </span>
                    </li>
                {% endif %}
                {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link" href="{{ own_url }}&page={{ page_obj.paginator.num_pages }}">Последняя</a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    </nav>
{% endif %}

<footer class="border-top text-center py-3">
  <p>Yaroslav Kuznetsov ©</p>
</footer>

templates/includes/header.html
{% load static %}
{% load django_bootstrap5 %}

<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="{% url 'projectForDBD:index' %}">
        <img src="{% static 'img/logo.png' %}" height="50" class="d-inline-block align-top" alt="">
      </a>

      <div 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
        >
        <span class="navbar-toggler-icon"></span>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        {% with request.resolver_match.view_name as view_name %}            
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'projectForDBD:index' %} active {% endif %}"
              href="{% url 'projectForDBD:index' %}"
              >
              Главная
            </a>
          </li>

          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'projectForDBD:product_list' %} active {% endif %}"
              href="{% url 'projectForDBD:product_list' %}"
              >
              Каталог товаров
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'projectForDBD:supplier_list' %} active {% endif %}"
              href="{% url 'projectForDBD:supplier_list' %}"
            >
              Поставщики
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'projectForDBD:category_list' %} active {% endif %}"
              href="{% url 'projectForDBD:category_list' %}"
            >
              Категории
            </a>
          </li>
        
          <li class="nav-item">
            <a
              class="nav-link {% if view_name == 'projectForDBD:cart' %} active {% endif %}"
              href="{% url 'projectForDBD:cart' %}"
            >
              Корзина
            </a>
          </li>



          {% if admin %}
            <li class="nav-item">
            <a
              class="nav-link"
              href="/admin/"
              style="background-color: orangered; color: black;"
            >
              Админ-панель
            </a>
            </li>
          {% endif %}

        </ul>
        {% endwith %}
      </div>

      <div>
      <div style="border: 2px solid darkgray; border-radius: 10px; padding: 4px;">
      <div class="card-body">
          {% if user and user.email %}

              <p class="nav-item" style="display: inline;" >{{ user.first_name }} {{ user.last_name }}</p>
              <pre class="nav-item" style="display: inline; width: 8px"> </pre>
              <form class="nav-item"  style="display: inline; width: 8px" method="post" action="/logout/">
                  {% csrf_token %}
                  {% bootstrap_button button_type="submit" content="Выйти" button_class="btn-warning" %}
              </form>
          {% else %}
              <p class="nav-item" style="display: inline;" > Не авторизован</p>
              {% bootstrap_button button_type="link" content="Войти" href="/login/" button_class="btn-success" %}
          {% endif %}
      </div>
      </div>

      </div>
    </div>
  </nav>
</header>