djangoProject/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),

# Логин.
    path('login/', views.LoginView.as_view(), name='login'),
    # Логаут.
    path('logout/', views.LogoutView.as_view(), name='logout'),

    # Изменение пароля.
    path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # Сообщение об успешном изменении пароля.
    path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Восстановление пароля.
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # Сообщение об отправке ссылки для восстановления пароля.
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # Вход по ссылке для восстановления пароля.
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Сообщение об успешном восстановлении пароля.
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('', include('projectForDBD.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectForDBD/urls.py
from django.urls import path

from . import views

app_name = 'projectForDBD'

urlpatterns = [
    path('', views.index, name='index'),

    path('products/', views.product_list, name='product_list'),
    path('categories/', views.category_list, name='category_list'),
    path('suppliers/', views.supplier_list, name='supplier_list'),

    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/<int:pk>/', views.remove_from_cart, name='delete_from_cart'),
    path('cart/', views.show_cart, name='cart'),

    path('category/create/', views.category_create, name='category_create'),
    path('category/edit/<int:pk>/', views.category_edit, name='category_edit'),
    path('category/delete/<int:pk>/', views.category_delete, name='category_delete'),
    path('supplier/create/', views.supplier_create, name='supplier_create'),
    path('supplier/edit/<int:pk>/', views.supplier_edit, name='supplier_edit'),
    path('supplier/delete/<int:pk>/', views.supplier_delete, name='supplier_delete'),
    path('product/create/', views.product_create, name='product_create'),
    path('product/edit/<int:pk>/', views.product_edit, name='product_edit'),
    path('product/delete/<int:pk>/', views.product_delete, name='product_delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.png' %}" type="image">
    {% bootstrap_css %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main class="pt-5 my-5">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
  <!--script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script-->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</html>

templates/cart.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Каталог товаров
{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center; justify-content: space-around;">
        <div class="card col-8 row-12">

            <div class="card-body">
                <form method="get">
                    {% bootstrap_form filter.form %}
                    {% bootstrap_button button_type="submit" content="Фильтровать" %}
                    {% if admin %}
                        {% url 'projectForDBD:product_create' as add_url %}
                    {% endif %}
                </form>
            </div>

        </div>

    </div>
    <br>

    <article class="mb-5">
    {% for product in page_obj %}
        <div style="display: flex; align-items: center; justify-content: space-around; margin-bottom: 4px; margin-top: 4px;">
            <div class="card" style="width: 40rem;">
              <div class="card-body">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" height="256px" width="256px">
                {% else %}
                    <img src="/product_images/noimage_10iswSl.webp" class="card-img-top" alt="Image not found" height="256px" width="256px">
                {% endif %}
                <h5 class="card-title">{{ product.title }} - {{ product.price }}₽</h5>
                <h6 class="card-subtitle mb-2 text-muted">
                   <small>
                        {{ product.description }}
                    </small>
                </h6>
                <p class="card-text">{{ post.text|truncatewords:10 }}</p>

                <button class="add-to-cart btn-warning btn delete-from-cart" data-product-id="{{ product.id }}">Удалить</button>
                <a href="{% url 'projectForDBD:product_edit' product.id %}" class="card-link">Подробнее</a>

              </div>
            </div>
        </div>

    {% endfor %}
    </article>

    <script>
    $(document).ready(function() {
        $('.delete-from-cart').click(function(e) {
            e.preventDefault();
            var $button = $(this);  // Сохраняем ссылку на кнопку
            var productId = $button.data('product-id');
            $.ajax({
                url: '/delete_from_cart/' + productId + '/',
                type: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response) {
                    // alert('Товар удалён из корзины');
                    $button.addClass('disabled btn-secondary').removeClass('btn-success');
                    $button.prop('disabled', true);
                    $button.text('Удалено из корзтны');
                },
                error: function(xhr, errmsg, err) {
                    alert('Ошибка при добавлении товара в корзину');
                }
            });
        });
    });
    </script>

{% endblock %}

templates/category_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Категории
{% endblock %}

{% block content %}
    
    <div style="display: flex; align-items: center; justify-content: space-around;">
        <div class="card col-8 row-12">

            <div class="card-body">
                <form method="get">
                    {% bootstrap_form filter.form %}
                    {% bootstrap_button button_type="submit" content="Фильтровать" %}
                    
                    {% if admin %}
                        {% url 'projectForDBD:category_create' as add_url %}
                        {% bootstrap_button button_type="link" content="Добавить новую запись" href=add_url button_class="btn-success" %}
                    {% endif %}
                </form>
            </div>

        </div>

    </div>
    <br>
    
    <article class="mb-5">
    {% for category in page_obj %}
        <div style="display: flex; align-items: center; justify-content: space-around; margin-bottom: 4px; margin-top: 4px;">
            <div class="card" style="width: 40rem;">
              <div class="card-body">
                <h5 class="card-title">{{ category.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">
                    <small>
                        {{ category.description }}
                    </small>
                </h6>
                  
                {% if admin %}
                    <!--<a href="" class="btn-info">Изменить</a>  button_class="btn-success" -->
                    {% url 'projectForDBD:category_edit' category.id as edit_url %}
                    {% bootstrap_button button_type="link" content="Изменить" href=edit_url %}
                    
                    {% url 'projectForDBD:category_delete' category.id as delete_url %}
                    {% bootstrap_button button_type="link" content="Удалить" href=delete_url button_class="btn-danger" %}
                {% else %}
                    <a href="{% url 'projectForDBD:category_edit' category.id %}" class="card-link">Подробнее</a>
                {% endif %}

              </div>
            </div>
        </div>

    {% endfor %}
    </article>
    


{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Главная
{% endblock %}

{% block content %}
<div style="align-items: center; justify-content: center; align-content: center; justify-items: center;">
    <img src="/static/img/logo.png" height="256px" class="d-inline-block align-top" alt="">
    <br>
    <h2 style="margin-top: 16px">Самый лучший магазин стройматериалов</h2>

    <h3>На сайте {{ products_count }} товаров.</h3>
</div>
{% endblock %}

templates/main_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Изменение в модель "{{ model_name }}"
{% endblock %}

{% block content %}
    
    <div style="display: flex; align-items: center; justify-content: space-around;">
        <div class="card col-8 row-12">

            <div class="card-body">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button button_type="submit" content="Применить" %}
                </form>
                
                {% if error %}
                    <br>
                    <div class="alert alert-danger" role="alert">
                        <h4>{{ error }}</h4>
                    </div>
                {% endif %}
            </div>

        </div>

    </div>
    
{% endblock %}

templates/product_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Каталог товаров
{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center; justify-content: space-around;">
        <div class="card col-8 row-12">

            <div class="card-body">
                <form method="get">
                    {% bootstrap_form filter.form %}
                    {% bootstrap_button button_type="submit" content="Фильтровать" %}
                    {% if admin %}
                        {% url 'projectForDBD:product_create' as add_url %}
                        {% bootstrap_button button_type="link" content="Добавить новую запись" href=add_url button_class="btn-success" %}
                    {% endif %}
                </form>
            </div>

        </div>

    </div>
    <br>

    <article class="mb-5">
    {% for product in page_obj %}
        <div style="display: flex; align-items: center; justify-content: space-around; margin-bottom: 4px; margin-top: 4px;">
            <div class="card" style="width: 40rem;">
              <div class="card-body">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" height="256px" width="256px">
                {% else %}
                    <img src="/product_images/noimage_10iswSl.webp" class="card-img-top" alt="{{ product.name }}" height="256px" width="256px">
                {% endif %}
                <h5 class="card-title">{{ product.title }} - {{ product.price }}₽</h5>
                <h6 class="card-subtitle mb-2 text-muted">
                   <small>
                        {{ product.description }}
                    </small>
                </h6>
                <p class="card-text">{{ post.text|truncatewords:10 }}</p>

                {% if admin %}
                    <!--<a href="" class="btn-info">Изменить</a>  button_class="btn-success" -->
                    {% url 'projectForDBD:product_edit' product.id as edit_url %}
                    {% bootstrap_button button_type="link" content="Изменить" href=edit_url %}

                    {% url 'projectForDBD:product_delete' product.id as delete_url %}
                    {% bootstrap_button button_type="link" content="Удалить" href=delete_url button_class="btn-danger" %}
                {% else %}
                    <a href="{% url 'projectForDBD:product_edit' product.id %}" class="card-link">Подробнее</a>
                {% endif %}

                {% if product.id not in cart %}
                    <button class="add-to-cart btn-success btn" data-product-id="{{ product.id }}">В корзину</button>
                {% else %}
                    <button class="btn-secondary btn disabled" data-product-id="{{ product.id }}">Уже в корзине</button>
                {% endif %}

              </div>
            </div>
        </div>

    {% endfor %}
    </article>

    <script>
$(document).ready(function() {
    $('.add-to-cart').click(function(e) {
        e.preventDefault();
        var $button = $(this);  // Сохраняем ссылку на кнопку
        var productId = $button.data('product-id');
        $.ajax({
            url: '/add_to_cart/' + productId + '/',
            type: 'POST',
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function(response) {
                //alert('Товар добавлен в корзину');
                $button.addClass('disabled btn-secondary').removeClass('btn-success');
                $button.prop('disabled', true);
                $button.text('Добавлено');
            },
            error: function(xhr, errmsg, err) {
                alert('Ошибка при добавлении товара в корзину');
            }
        });
    });
});
    </script>

{% endblock %}

templates/supplier_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Поставщики
{% endblock %}

{% block content %}
    <div style="display: flex; align-items: center; justify-content: space-around;">
        <div class="card col-8 row-12">

            <div class="card-body">
                <form method="get">
                    {% bootstrap_form filter.form %}
                    {% bootstrap_button button_type="submit" content="Фильтровать" %}
                    {% if admin %}
                        {% url 'projectForDBD:supplier_create' as add_url %}
                        {% bootstrap_button button_type="link" content="Добавить новую запись" href=add_url button_class="btn-success" %}
                    {% endif %}
                    
                </form>
            </div>

        </div>

    </div>
    <br>

    
    <article class="mb-5">
    {% for supplier in page_obj %}
        <div style="display: flex; align-items: center; justify-content: space-around; margin-bottom: 4px; margin-top: 4px;">
            <div class="card" style="width: 40rem;">
              <div class="card-body">
                <h5 class="card-title">{{ supplier.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">
                    <small>
                        {{ supplier.contact_info }}
                    </small>

                </h6>
                <!--p class="card-text">{{ post.text|truncatewords:10 }}</p-->
                {% if admin %}
                    <!--<a href="" class="btn-info">Изменить</a>  button_class="btn-success" -->
                    {% url 'projectForDBD:supplier_edit' supplier.id as edit_url %}
                    {% bootstrap_button button_type="link" content="Изменить" href=edit_url %}
                    
                    {% url 'projectForDBD:supplier_delete' supplier.id as delete_url %}
                    {% bootstrap_button button_type="link" content="Удалить" href=delete_url button_class="btn-danger" %}
                {% else %}
                    <a href="{% url 'projectForDBD:supplier_edit' supplier.id %}" class="card-link">Подробнее</a>
                {% endif %}

              </div>
            </div>
        </div>

    {% endfor %}
    </article>


{% endblock %}